# copyright: 2023 EUMETSAT
# license: LICENSE.txt
name: cmts_learn_osi_saf_wind
channels:
  - conda-forge
  - eumetsat
dependencies:
  - conda-forge::python=3.9
  - conda-forge::jupyterlab
  - conda-forge::netcdf4
  - conda-forge::matplotlib
  - conda-forge::cartopy
  - conda-forge::ipywidgets
  - conda-forge::jupyter_nbextensions_configurator
  - conda-forge::ipykernel
  - conda-forge::cmocean
  - conda-forge::cmcrameri
  - conda-forge::xarray
  - conda-forge::pydap
  - conda-forge::owslib
  - eumetsat::eumdac